rootLogger.level = warn
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = console

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss} %-5p %c{1}: %m%n

logger.spark.name = org.apache.spark
logger.spark.level = warn

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = warn
